"""A BATCH JOB MUST NOT DIE ON SOMEONE ELSE'S CTRL-C.

ATTRIBUTED 2026-08-04 after SIX deaths in one day, every one exiting `0xC000013A`
(STATUS_CONTROL_C_EXIT) with `^C` in the log. The scheduled task runs `LogonType: Interactive`, so
it lands in the user's interactive session — MEASURED: campaign `sessionId 1`, agent shell
`sessionId 1`, the same session. A CTRL_C generated by any long-running command there is broadcast
to the console process group and takes the campaign with it. Five of the six deaths coincided with a
long foreground command; a SHORT one was controlled for and never did it.

⛔ THE REAL FIX IS THE SESSION (`-LogonType S4U`) AND IT NEEDS ELEVATION, which the agent process
does not have — `Set-ScheduledTaskPrincipal` returned "Access is denied". This shield stops the
SYMPTOM in the meantime, and the two are not alternatives: apply S4U when you can.

⭐ THE BEHAVIOURAL TEST IS THE POINT. Asserting `signal.getsignal(SIGINT) is SIG_IGN` proves only
that a line ran. These tests SPAWN A REAL CHILD, deliver a real SIGINT, and read the exit code — and
the unshielded child is the control that proves the signal is genuinely lethal in this environment.
Without that control, a shielded child surviving would prove nothing: it might simply never have
been signalled.
"""
import os
import subprocess
import sys
import textwrap

import pytest

backend_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)
sys.path.insert(0, os.path.join(backend_dir, "scripts"))

import era5_deepen_climatology as E                                    # noqa: E402

SCRIPTS = os.path.join(backend_dir, "scripts")

_CHILD = textwrap.dedent("""
    import signal, sys
    sys.path.insert(0, r"{backend}")
    sys.path.insert(0, r"{scripts}")
    import era5_deepen_climatology as E
    if {shield}:
        E.install_interrupt_shield(force=True)
    try:
        signal.raise_signal(signal.SIGINT)
    except KeyboardInterrupt:
        sys.stdout.write("DIED"); sys.stdout.flush(); sys.exit(3)
    sys.stdout.write("SURVIVED"); sys.stdout.flush(); sys.exit(0)
""")


def _run_child(shield):
    src = _CHILD.format(backend=backend_dir, scripts=SCRIPTS, shield=bool(shield))
    # ⚠️ stdin=DEVNULL is REQUIRED, not tidiness: under pytest's capture the parent's standard
    # handles are replaced and `subprocess` cannot duplicate them, so an inherited stdin raises
    # `OSError: [WinError 6] The handle is invalid` before the child ever starts. That failure looks
    # exactly like "the control did not die", which would have voided the experiment.
    p = subprocess.run([sys.executable, "-c", src], stdin=subprocess.DEVNULL,
                       stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=180)
    return p.returncode, (p.stdout or "").strip()


# ── the experiment, with its control ────────────────────────────────────────────────────────────

def test_CONTROL_an_unshielded_run_really_does_die_on_sigint():
    """The control that makes the next test mean something: without the shield, SIGINT is lethal."""
    code, out = _run_child(shield=False)
    assert out == "DIED", f"setup: the unshielded child did not take the interrupt (out={out!r})"
    assert code == 3


def test_a_shielded_run_survives_the_same_interrupt():
    """The behaviour the shield exists for — same signal, same environment, different outcome."""
    code, out = _run_child(shield=True)
    assert out == "SURVIVED", f"the shield did not hold (out={out!r}, exit={code})"
    assert code == 0


# ── when it engages ─────────────────────────────────────────────────────────────────────────────

def test_shield_is_ON_when_stdout_is_redirected(monkeypatch):
    """Under the scheduled task stdout goes to a log file, so nobody is watching to press Ctrl-C."""
    monkeypatch.setattr(sys, "stdout", type("S", (), {"isatty": staticmethod(lambda: False)})())
    monkeypatch.delenv("ERA5_INTERRUPT_SHIELD", raising=False)
    assert E._shield_wanted() is True


def test_shield_is_OFF_in_a_terminal_so_a_human_keeps_control_c(monkeypatch):
    """⛔ The one outcome that would be user-hostile: a human running this by hand must still be
    able to stop it."""
    monkeypatch.setattr(sys, "stdout", type("S", (), {"isatty": staticmethod(lambda: True)})())
    monkeypatch.delenv("ERA5_INTERRUPT_SHIELD", raising=False)
    assert E._shield_wanted() is False


@pytest.mark.parametrize("val,expected", [("1", True), ("true", True), ("ON", True),
                                          ("0", False), ("false", False), ("off", False)])
def test_env_var_overrides_the_autodetect_both_ways(monkeypatch, val, expected):
    monkeypatch.setenv("ERA5_INTERRUPT_SHIELD", val)
    # tty says the opposite of the override, so only the override can produce `expected`
    monkeypatch.setattr(sys, "stdout",
                        type("S", (), {"isatty": staticmethod(lambda: expected)})())
    assert E._shield_wanted() is expected


def test_a_detached_stdout_that_raises_still_shields(monkeypatch):
    """`isatty` can raise on a detached handle. Unknowable => shield, because the cost of a wrong
    guess is asymmetric: a needlessly shielded batch job is stoppable by Stop-ScheduledTask, an
    unshielded one loses hours of unbanked work."""
    class Boom:
        @staticmethod
        def isatty():
            raise OSError("detached")
    monkeypatch.setattr(sys, "stdout", Boom())
    monkeypatch.delenv("ERA5_INTERRUPT_SHIELD", raising=False)
    assert E._shield_wanted() is True


def test_install_returns_false_and_does_not_raise_when_not_wanted(monkeypatch):
    monkeypatch.setattr(sys, "stdout", type("S", (), {"isatty": staticmethod(lambda: True)})())
    monkeypatch.delenv("ERA5_INTERRUPT_SHIELD", raising=False)
    assert E.install_interrupt_shield() is False


def test_the_shield_is_narrow_by_design():
    """It must NOT swallow the ways this job is legitimately stopped: `Stop-ScheduledTask`, the
    liveness reaper's `psutil.kill`, or a real shutdown. Only SIGINT is touched — asserted from the
    source so a later edit that widens it has to justify itself here."""
    import inspect
    src = inspect.getsource(E.install_interrupt_shield)
    # ⚠️ STRIP THE DOCSTRING FIRST. The first version of this test read the whole source and failed
    # on its own prose — the docstring NAMES SIGTERM precisely to say it is not covered. That is the
    # documented substring-guard trap in this repo (`test_surf_transform_docstring_truth`): a text
    # check cannot tell a live claim from a quotation about one. Assert on the BODY.
    parts = src.split('"""')
    body = parts[2] if len(parts) >= 3 else src
    assert "SIGINT" in body, "the shield no longer touches SIGINT at all"
    for wider in ("SIGTERM", "SIGBREAK", "CTRL_CLOSE", "SIGHUP"):
        assert wider not in body, (
            f"the shield now also covers {wider} — that would block a deliberate "
            f"Stop-ScheduledTask, the liveness reaper, or a real shutdown")
