"""
Password hashing must survive the removal of the stdlib `crypt` module (Python 3.13+).

⚠️ THIS FILE EXISTS BECAUSE I RECORDED A FALSE BLOCKER. When CI moved to 3.12 the suite emitted
    passlib/utils/__init__.py:854: DeprecationWarning: 'crypt' is deprecated and slated for
    removal in Python 3.13
and I wrote down "passlib blocks 3.13" and carried it into a handoff. That was an INFERENCE FROM A
WARNING, never executed. passlib 1.7.4 actually guards the import:

    try:
        from crypt import crypt as _crypt
    except ImportError:   # pragma: no cover
        _crypt = None

so on 3.13+ it simply sets `_crypt = None` and carries on. Verified by execution on Python 3.14.4,
where `import crypt` raises ModuleNotFoundError and passlib still hashes and verifies.
★ THE LESSON IS THE SHAPE: a DeprecationWarning announces a POSSIBILITY, never a failure. The same
  session had already turned "zarr is installed" into "zarr is used" the same way. Execute the
  claim, or do not record it.

★★ AND THE POINT OF THE TEST BELOW IS THAT IT DOES NOT NEED 3.13. It removes `crypt` from the
   import system and re-imports passlib, so the 3.13 property is asserted on whatever interpreter
   CI happens to run — today 3.12, where `crypt` still exists and the warning still fires. A claim
   about a future interpreter that can only be checked on that interpreter is a claim nobody checks.

The frozen-hash cases are the anti-lockout guard: they are real bcrypt hashes produced by the
current configuration, and they must keep verifying through any future change to how passwords are
hashed. If a refactor breaks them, every existing user is locked out.
"""
import sys

import pytest

# Exactly the context all six call sites construct (auth.py, password_reset.py, admin/core.py,
# grom_hq/parental.py, grom_hq/verification.py, scripts/seed_david_profile.py).
SCHEMES = ["bcrypt"]

# Real $2b$ hashes generated by CryptContext(schemes=["bcrypt"], deprecated="auto").
# ⚠️ NEVER REGENERATE THESE TO MAKE A TEST PASS. Their whole value is that they were produced by the
# implementation as it stood on 2026-08-06 — regenerating them under a new implementation would
# assert only that the new code agrees with itself.
FROZEN = [
    ("correct horse battery staple",
     "$2b$12$qOc2aZVxWW6pNmrz.J1qe.PKE9BgEDI.99bVu5GZXhAyy/gHmtumq"),
    ("p@ssw0rd!",
     "$2b$12$fo2k41wji2SWzdcZtv1lvucpZ3k7ZJWaR/REAl.dSty7wgoMCMpM."),
]


def fresh_context():
    from passlib.context import CryptContext
    return CryptContext(schemes=SCHEMES, deprecated="auto")


# ── The 3.13 property, asserted on today's interpreter ────────────────────────

@pytest.fixture
def without_crypt(monkeypatch):
    """Make `import crypt` fail the way Python 3.13+ does, then force passlib to re-import.

    Setting a sys.modules entry to None is the documented way to make an import raise ImportError.
    monkeypatch restores both the entry and the evicted passlib modules afterwards, so this cannot
    leak into other tests.
    """
    monkeypatch.setitem(sys.modules, "crypt", None)
    for name in [m for m in list(sys.modules) if m == "passlib" or m.startswith("passlib.")]:
        monkeypatch.delitem(sys.modules, name, raising=False)
    return monkeypatch


def test_crypt_really_is_unimportable_under_the_fixture(without_crypt):
    """CONTROL. If this fails, the fixture is not simulating 3.13 and every test below is vacuous."""
    with pytest.raises(ImportError):
        import crypt  # noqa: F401


def test_the_simulation_is_only_a_simulation_below_3_13():
    """
    ⚠️ WITHOUT THIS, THE CONTROL ABOVE PASSES FOR THE WRONG REASON ON 3.13+. There `crypt` is
    genuinely gone, so the fixture removes nothing and "it passed" says only that the interpreter
    already lacks the module — not that the fixture works.
    ⇒ State which case we are in, so a green run cannot be read as a simulation that never ran.
      Below 3.13 the module MUST be natively importable (the simulation is doing real work);
      at 3.13+ it MUST NOT be (the fixture is a no-op and the tests are then direct evidence).
    """
    try:
        import crypt  # noqa: F401
        natively_present = True
    except ImportError:
        natively_present = False

    if sys.version_info < (3, 13):
        assert natively_present, (
            "crypt is missing below 3.13 — the `without_crypt` fixture would be removing something "
            "that was never there, making every simulation test vacuous"
        )
    else:
        assert not natively_present, (
            "crypt is importable on 3.13+, which contradicts the removal these tests are about"
        )


def test_passlib_imports_without_the_crypt_module(without_crypt):
    import passlib.utils

    assert passlib.utils._crypt is None, (
        "passlib imported a crypt module that is supposed to be unavailable — the fixture is not "
        "isolating the import"
    )


def test_hash_and_verify_work_without_the_crypt_module(without_crypt):
    ctx = fresh_context()
    hashed = ctx.hash("correct horse battery staple")
    assert hashed.startswith("$2b$")
    assert ctx.verify("correct horse battery staple", hashed) is True
    assert ctx.verify("wrong password", hashed) is False


@pytest.mark.parametrize("password, hashed", FROZEN)
def test_frozen_hashes_still_verify_without_the_crypt_module(without_crypt, password, hashed):
    """The anti-lockout guard, under the 3.13 simulation."""
    assert fresh_context().verify(password, hashed) is True


# ── The same guarantees on the interpreter actually in use ────────────────────

@pytest.mark.parametrize("password, hashed", FROZEN)
def test_frozen_hashes_still_verify(password, hashed):
    ctx = fresh_context()
    assert ctx.verify(password, hashed) is True
    assert ctx.verify(password + "x", hashed) is False


def test_passlib_and_raw_bcrypt_verify_each_others_hashes():
    """
    Pre-clears a future removal of passlib, which is unmaintained since 2020 and is used here only
    as a thin wrapper over bcrypt — every call site is `schemes=["bcrypt"]`.
    If these two agree in BOTH directions, dropping passlib is a mechanical change that cannot lock
    anyone out, and a rollback is equally safe. If they ever disagree, it is not.
    """
    import bcrypt

    ctx = fresh_context()
    secret = b"correct horse battery staple"

    from_passlib = ctx.hash(secret.decode())
    assert bcrypt.checkpw(secret, from_passlib.encode()), "raw bcrypt cannot verify a passlib hash"

    from_bcrypt = bcrypt.hashpw(secret, bcrypt.gensalt()).decode()
    assert ctx.verify(secret.decode(), from_bcrypt), "passlib cannot verify a raw bcrypt hash"

    for _, frozen in FROZEN:
        assert bcrypt.checkpw(FROZEN[0][0].encode(), FROZEN[0][1].encode())


def test_every_call_site_uses_the_same_scheme():
    """
    Six independent CryptContext constructions is six chances to drift. A site that quietly picked a
    different scheme would still pass its own tests while writing hashes the others cannot verify.
    """
    import pathlib
    import re

    backend = pathlib.Path(__file__).resolve().parent.parent
    pattern = re.compile(r"CryptContext\(\s*schemes\s*=\s*\[([^\]]*)\]")
    found = {}
    for path in backend.rglob("*.py"):
        if "tests" in path.parts or "site-packages" in str(path):
            continue
        for match in pattern.finditer(path.read_text(encoding="utf-8", errors="ignore")):
            found[str(path.relative_to(backend))] = match.group(1).strip()

    assert found, "no CryptContext call sites found — this guard has lost its subject"
    schemes = set(found.values())
    assert schemes == {'"bcrypt"'}, f"call sites disagree on the hashing scheme: {found}"
