"""add_selection_deadline_and_auto_select_on_expiry

Revision ID: 10279d0ca1fd
Revises: d42bb546bc54
Create Date: 2026-04-07 03:32:37.316524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10279d0ca1fd'
down_revision: Union[str, Sequence[str], None] = 'd42bb546bc54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galleries', sa.Column('booking_id', sa.String(length=36), nullable=True))
    op.add_column('galleries', sa.Column('dispatch_id', sa.String(length=36), nullable=True))
    op.add_column('galleries', sa.Column('session_type', sa.String(length=30), nullable=True))
    op.add_column('galleries', sa.Column('locked_price_web', sa.Float(), nullable=True))
    op.add_column('galleries', sa.Column('locked_price_standard', sa.Float(), nullable=True))
    op.add_column('galleries', sa.Column('locked_price_high', sa.Float(), nullable=True))
    op.add_column('galleries', sa.Column('default_tier', sa.Enum('STANDARD', 'PRO', name='gallerytierenum'), nullable=True))
    op.add_column('galleries', sa.Column('is_for_sale', sa.Boolean(), nullable=True))
    op.add_column('galleries', sa.Column('show_watermark_in_selection', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_galleries_booking_id'), 'galleries', ['booking_id'], unique=False)
    op.create_index(op.f('ix_galleries_dispatch_id'), 'galleries', ['dispatch_id'], unique=False)
    op.create_foreign_key(None, 'galleries', 'dispatch_requests', ['dispatch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'galleries', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    op.add_column('surfer_selection_quotas', sa.Column('gallery_id', sa.String(length=36), nullable=True))
    op.add_column('surfer_selection_quotas', sa.Column('auto_select_on_expiry', sa.Boolean(), nullable=True))
    op.add_column('surfer_selection_quotas', sa.Column('expiry_reminder_sent', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_surfer_selection_quotas_gallery_id'), 'surfer_selection_quotas', ['gallery_id'], unique=False)
    op.create_foreign_key(None, 'surfer_selection_quotas', 'galleries', ['gallery_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surfer_selection_quotas', type_='foreignkey')
    op.drop_index(op.f('ix_surfer_selection_quotas_gallery_id'), table_name='surfer_selection_quotas')
    op.drop_column('surfer_selection_quotas', 'expiry_reminder_sent')
    op.drop_column('surfer_selection_quotas', 'auto_select_on_expiry')
    op.drop_column('surfer_selection_quotas', 'gallery_id')
    op.drop_constraint(None, 'galleries', type_='foreignkey')
    op.drop_constraint(None, 'galleries', type_='foreignkey')
    op.drop_index(op.f('ix_galleries_dispatch_id'), table_name='galleries')
    op.drop_index(op.f('ix_galleries_booking_id'), table_name='galleries')
    op.drop_column('galleries', 'show_watermark_in_selection')
    op.drop_column('galleries', 'is_for_sale')
    op.drop_column('galleries', 'default_tier')
    op.drop_column('galleries', 'locked_price_high')
    op.drop_column('galleries', 'locked_price_standard')
    op.drop_column('galleries', 'locked_price_web')
    op.drop_column('galleries', 'session_type')
    op.drop_column('galleries', 'dispatch_id')
    op.drop_column('galleries', 'booking_id')
    # ### end Alembic commands ###
