"""add_tos_compliance_system

Revision ID: 16d4062ae064
Revises: c89872c7b8ae
Create Date: 2026-04-07 03:54:35.416071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d4062ae064'
down_revision: Union[str, Sequence[str], None] = 'c89872c7b8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('suspension_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('is_banned', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('tos_strike_count', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('tos_last_violation_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'tos_last_violation_at')
    op.drop_column('profiles', 'tos_strike_count')
    op.drop_column('profiles', 'banned_at')
    op.drop_column('profiles', 'is_banned')
    op.drop_column('profiles', 'suspension_until')
    # ### end Alembic commands ###
