"""Add booking splitting and invites

Revision ID: 2eba5ff663be
Revises: b28faba965d1
Create Date: 2026-03-15 00:29:04.848238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eba5ff663be'
down_revision: Union[str, Sequence[str], None] = 'b28faba965d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('inviter_id', sa.String(length=36), nullable=False),
    sa.Column('invitee_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitee_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_invites_booking_id'), 'booking_invites', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_invites_invitee_id'), 'booking_invites', ['invitee_id'], unique=False)
    op.create_index(op.f('ix_booking_invites_inviter_id'), 'booking_invites', ['inviter_id'], unique=False)
    op.add_column('booking_participants', sa.Column('invited_by_id', sa.String(length=36), nullable=True))
    op.add_column('booking_participants', sa.Column('invite_type', sa.String(length=30), nullable=True))
    op.add_column('booking_participants', sa.Column('payment_method', sa.String(length=30), nullable=True))
    op.add_column('booking_participants', sa.Column('status', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'booking_participants', 'profiles', ['invited_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('bookings', sa.Column('creator_id', sa.String(length=36), nullable=True))
    op.add_column('bookings', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('total_price', sa.Float(), nullable=False))
    op.add_column('bookings', sa.Column('price_per_person', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('allow_splitting', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('split_mode', sa.String(length=30), nullable=True))
    op.add_column('bookings', sa.Column('invite_code', sa.String(length=10), nullable=True))
    op.add_column('bookings', sa.Column('proximity_radius', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_bookings_creator_id'), 'bookings', ['creator_id'], unique=False)
    op.create_unique_constraint(None, 'bookings', ['invite_code'])
    op.create_foreign_key(None, 'bookings', 'profiles', ['creator_id'], ['id'], ondelete='SET NULL')
    op.drop_column('bookings', 'hourly_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('hourly_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='unique')
    op.drop_index(op.f('ix_bookings_creator_id'), table_name='bookings')
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'proximity_radius')
    op.drop_column('bookings', 'invite_code')
    op.drop_column('bookings', 'split_mode')
    op.drop_column('bookings', 'allow_splitting')
    op.drop_column('bookings', 'price_per_person')
    op.drop_column('bookings', 'total_price')
    op.drop_column('bookings', 'description')
    op.drop_column('bookings', 'duration')
    op.drop_column('bookings', 'longitude')
    op.drop_column('bookings', 'latitude')
    op.drop_column('bookings', 'creator_id')
    op.drop_constraint(None, 'booking_participants', type_='foreignkey')
    op.drop_column('booking_participants', 'status')
    op.drop_column('booking_participants', 'payment_method')
    op.drop_column('booking_participants', 'invite_type')
    op.drop_column('booking_participants', 'invited_by_id')
    op.drop_index(op.f('ix_booking_invites_inviter_id'), table_name='booking_invites')
    op.drop_index(op.f('ix_booking_invites_invitee_id'), table_name='booking_invites')
    op.drop_index(op.f('ix_booking_invites_booking_id'), table_name='booking_invites')
    op.drop_table('booking_invites')
    # ### end Alembic commands ###
