"""Add impact score and verified causes

Revision ID: 2f7c6bd5fa7d
Revises: 34c51b411ea3
Create Date: 2026-03-15 03:27:34.403824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7c6bd5fa7d'
down_revision: Union[str, Sequence[str], None] = '34c51b411ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verified_causes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('total_donations', sa.Float(), nullable=True),
    sa.Column('donor_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('instant_shaka_videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('sponsorship_id', sa.String(length=36), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('is_viewed', sa.Boolean(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sponsorship_id'], ['sponsorship_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instant_shaka_videos_recipient_id'), 'instant_shaka_videos', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_instant_shaka_videos_sender_id'), 'instant_shaka_videos', ['sender_id'], unique=False)
    
    # Add columns with server defaults for existing rows
    op.add_column('profiles', sa.Column('total_credits_given', sa.Float(), nullable=True, server_default='0.0'))
    op.add_column('profiles', sa.Column('total_groms_supported', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('profiles', sa.Column('total_causes_supported', sa.Integer(), nullable=True, server_default='0'))
    
    # Update nulls and set NOT NULL constraint
    op.execute("UPDATE profiles SET total_credits_given = 0.0 WHERE total_credits_given IS NULL")
    op.alter_column('profiles', 'total_credits_given', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'total_causes_supported')
    op.drop_column('profiles', 'total_groms_supported')
    op.drop_column('profiles', 'total_credits_given')
    op.drop_index(op.f('ix_instant_shaka_videos_sender_id'), table_name='instant_shaka_videos')
    op.drop_index(op.f('ix_instant_shaka_videos_recipient_id'), table_name='instant_shaka_videos')
    op.drop_table('instant_shaka_videos')
    op.drop_table('verified_causes')
    # ### end Alembic commands ###
