"""update_preferred_conditions_to_json

Revision ID: 2fd2888a0987
Revises: 4bc6043c0cc3
Create Date: 2026-04-08 15:40:07.207594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd2888a0987'
down_revision: Union[str, Sequence[str], None] = '4bc6043c0cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First convert existing string values to JSON arrays
    # Handle both NULL and existing string values
    op.execute("""
        UPDATE surf_alerts 
        SET preferred_conditions = 
            CASE 
                WHEN preferred_conditions IS NULL THEN NULL
                WHEN preferred_conditions = '' THEN NULL
                ELSE ('["' || REPLACE(preferred_conditions, ',', '","') || '"]')::json
            END::text
    """)
    
    # Now alter the column type
    op.alter_column('surf_alerts', 'preferred_conditions',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='preferred_conditions::json')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surf_alerts', 'preferred_conditions',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
