"""Add password_hash to profiles

Revision ID: 3035f09427fe
Revises: 9930f5ad0662
Create Date: 2026-03-14 20:52:32.678262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3035f09427fe'
down_revision: Union[str, Sequence[str], None] = '9930f5ad0662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'password_hash')
    # ### end Alembic commands ###
