"""Add gear savings and session destination fields

Revision ID: 34c51b411ea3
Revises: eca9b463bb3e
Create Date: 2026-03-15 03:11:31.642606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c51b411ea3'
down_revision: Union[str, Sequence[str], None] = 'eca9b463bb3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear_catalog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.Enum('CAMERA', 'LENS', 'HOUSING', 'DRONE', 'ACCESSORIES', 'SURFBOARD', 'WETSUIT', 'SURF_ACCESSORIES', name='gearcategory'), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('price_credits', sa.Float(), nullable=False),
    sa.Column('retail_price_usd', sa.Float(), nullable=True),
    sa.Column('affiliate_partner', sa.String(length=50), nullable=False),
    sa.Column('affiliate_url', sa.String(length=1000), nullable=False),
    sa.Column('affiliate_commission_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('stock_status', sa.String(length=30), nullable=True),
    sa.Column('purchase_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gear_purchases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('gear_item_id', sa.String(length=36), nullable=True),
    sa.Column('credits_spent', sa.Float(), nullable=False),
    sa.Column('affiliate_url_used', sa.String(length=1000), nullable=True),
    sa.Column('affiliate_partner', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gear_item_id'], ['gear_catalog.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gear_purchases_gear_item_id'), 'gear_purchases', ['gear_item_id'], unique=False)
    op.create_index(op.f('ix_gear_purchases_user_id'), 'gear_purchases', ['user_id'], unique=False)
    op.create_table('sponsorship_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('donor_id', sa.String(length=36), nullable=True),
    sa.Column('recipient_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('sponsorship_type', sa.Enum('PRO_SPONSORSHIP', 'IMPACT_DONATION', name='sponsorshiptype'), nullable=False),
    sa.Column('recipient_type', sa.String(length=30), nullable=False),
    sa.Column('cause_name', sa.String(length=255), nullable=True),
    sa.Column('source_transaction_type', sa.String(length=50), nullable=True),
    sa.Column('source_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('shaka_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorship_transactions_created_at'), 'sponsorship_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sponsorship_transactions_donor_id'), 'sponsorship_transactions', ['donor_id'], unique=False)
    op.create_index(op.f('ix_sponsorship_transactions_recipient_id'), 'sponsorship_transactions', ['recipient_id'], unique=False)
    op.create_table('shaka_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('sponsorship_id', sa.String(length=36), nullable=True),
    sa.Column('message_type', sa.String(length=30), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('animation_id', sa.String(length=50), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('post_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sponsorship_id'], ['sponsorship_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shaka_messages_recipient_id'), 'shaka_messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_shaka_messages_sender_id'), 'shaka_messages', ['sender_id'], unique=False)
    op.add_column('live_sessions', sa.Column('earnings_destination_type', sa.String(length=30), nullable=True))
    op.add_column('live_sessions', sa.Column('earnings_destination_id', sa.String(length=36), nullable=True))
    op.add_column('live_sessions', sa.Column('earnings_cause_name', sa.String(length=255), nullable=True))
    
    # Add columns with default values for existing rows
    op.add_column('profiles', sa.Column('withdrawable_credits', sa.Float(), nullable=True, server_default='0.0'))
    op.add_column('profiles', sa.Column('gear_only_credits', sa.Float(), nullable=True, server_default='0.0'))
    
    # Set NOT NULL constraint after default is applied
    op.execute("UPDATE profiles SET withdrawable_credits = 0.0 WHERE withdrawable_credits IS NULL")
    op.execute("UPDATE profiles SET gear_only_credits = 0.0 WHERE gear_only_credits IS NULL")
    op.alter_column('profiles', 'withdrawable_credits', nullable=False)
    op.alter_column('profiles', 'gear_only_credits', nullable=False)
    
    op.add_column('profiles', sa.Column('donation_destination_type', sa.String(length=30), nullable=True))
    op.add_column('profiles', sa.Column('donation_destination_id', sa.String(length=36), nullable=True))
    op.add_column('profiles', sa.Column('donation_cause_name', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('target_gear_item_id', sa.String(length=36), nullable=True))
    op.add_column('profiles', sa.Column('donation_split_percentage', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('stripe_connect_id', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('stripe_connected', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'gear_catalog', ['target_gear_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'stripe_connected')
    op.drop_column('profiles', 'stripe_connect_id')
    op.drop_column('profiles', 'donation_split_percentage')
    op.drop_column('profiles', 'target_gear_item_id')
    op.drop_column('profiles', 'donation_cause_name')
    op.drop_column('profiles', 'donation_destination_id')
    op.drop_column('profiles', 'donation_destination_type')
    op.drop_column('profiles', 'gear_only_credits')
    op.drop_column('profiles', 'withdrawable_credits')
    op.drop_column('live_sessions', 'earnings_cause_name')
    op.drop_column('live_sessions', 'earnings_destination_id')
    op.drop_column('live_sessions', 'earnings_destination_type')
    op.drop_index(op.f('ix_shaka_messages_sender_id'), table_name='shaka_messages')
    op.drop_index(op.f('ix_shaka_messages_recipient_id'), table_name='shaka_messages')
    op.drop_table('shaka_messages')
    op.drop_index(op.f('ix_sponsorship_transactions_recipient_id'), table_name='sponsorship_transactions')
    op.drop_index(op.f('ix_sponsorship_transactions_donor_id'), table_name='sponsorship_transactions')
    op.drop_index(op.f('ix_sponsorship_transactions_created_at'), table_name='sponsorship_transactions')
    op.drop_table('sponsorship_transactions')
    op.drop_index(op.f('ix_gear_purchases_user_id'), table_name='gear_purchases')
    op.drop_index(op.f('ix_gear_purchases_gear_item_id'), table_name='gear_purchases')
    op.drop_table('gear_purchases')
    op.drop_table('gear_catalog')
    # ### end Alembic commands ###
