"""Add SurfSpot and photographer live fields

Revision ID: 3c0cfb85ba5a
Revises: fa6d17d449bd
Create Date: 2026-03-14 14:26:40.886268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0cfb85ba5a'
down_revision: Union[str, Sequence[str], None] = 'fa6d17d449bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surf_spots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('best_tide', sa.String(length=100), nullable=True),
    sa.Column('best_swell', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surf_spots_name'), 'surf_spots', ['name'], unique=False)
    op.add_column('profiles', sa.Column('is_shooting', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('is_streaming', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('current_spot_id', sa.String(length=36), nullable=True))
    op.add_column('profiles', sa.Column('shooting_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('last_story_url', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'profiles', 'surf_spots', ['current_spot_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'last_story_url')
    op.drop_column('profiles', 'shooting_started_at')
    op.drop_column('profiles', 'current_spot_id')
    op.drop_column('profiles', 'is_streaming')
    op.drop_column('profiles', 'is_shooting')
    op.drop_index(op.f('ix_surf_spots_name'), table_name='surf_spots')
    op.drop_table('surf_spots')
    # ### end Alembic commands ###
