"""add_grom_safety_gate_fields

Revision ID: 3fd4454229d5
Revises: 872fd5e2e5b0
Create Date: 2026-04-01 02:13:22.796107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd4454229d5'
down_revision: Union[str, Sequence[str], None] = '872fd5e2e5b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_badges_user_id'), 'badges', ['user_id'], unique=False)
    op.drop_index(op.f('ix_competition_results_surfer'), table_name='competition_results')
    op.create_index(op.f('ix_competition_results_surfer_id'), 'competition_results', ['surfer_id'], unique=False)
    op.drop_index(op.f('idx_condition_reports_created'), table_name='condition_reports')
    op.drop_index(op.f('idx_condition_reports_photographer'), table_name='condition_reports')
    op.drop_index(op.f('idx_condition_reports_region'), table_name='condition_reports')
    op.create_index(op.f('ix_condition_reports_created_at'), 'condition_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_condition_reports_photographer_id'), 'condition_reports', ['photographer_id'], unique=False)
    op.create_index(op.f('ix_condition_reports_region'), 'condition_reports', ['region'], unique=False)
    op.create_index(op.f('ix_condition_reports_spot_id'), 'condition_reports', ['spot_id'], unique=False)
    op.drop_index(op.f('idx_unique_conversation_pair'), table_name='conversations')
    op.drop_index(op.f('ix_gold_pass_photographer'), table_name='gold_pass_bookings')
    op.create_index(op.f('ix_gold_pass_bookings_photographer_id'), 'gold_pass_bookings', ['photographer_id'], unique=False)
    op.drop_index(op.f('idx_live_session_participants_live_session_id'), table_name='live_session_participants')
    op.create_index(op.f('ix_live_session_participants_live_session_id'), 'live_session_participants', ['live_session_id'], unique=False)
    op.create_foreign_key(None, 'live_session_participants', 'live_sessions', ['live_session_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_messages_reply_to'), table_name='messages', postgresql_where='(reply_to_id IS NOT NULL)')
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_constraint(op.f('notification_preferences_user_id_key'), 'notification_preferences', type_='unique')
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.drop_index(op.f('idx_availability_photographer'), table_name='photographer_availability')
    op.create_index(op.f('ix_photographer_availability_photographer_id'), 'photographer_availability', ['photographer_id'], unique=False)
    op.add_column('profiles', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('profiles', sa.Column('guardian_code', sa.String(length=10), nullable=True))
    op.add_column('profiles', sa.Column('parent_link_approved', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('parent_age_verified', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('parental_controls', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'profiles', ['guardian_code'])
    op.drop_column('profiles', 'equipment')
    op.drop_index(op.f('ix_reviews_created'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewee'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_session'), table_name='reviews')
    op.create_index('ix_review_session_unique', 'reviews', ['reviewer_id', 'reviewee_id', 'live_session_id'], unique=True)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_live_session_id'), 'reviews', ['live_session_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewee_id'), 'reviews', ['reviewee_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.drop_index(op.f('idx_social_live_streams_broadcaster'), table_name='social_live_streams')
    op.create_index(op.f('ix_social_live_streams_broadcaster_id'), 'social_live_streams', ['broadcaster_id'], unique=False)
    op.drop_index(op.f('ix_sponsorships_surfer'), table_name='sponsorships')
    op.create_index(op.f('ix_sponsorships_surfer_id'), 'sponsorships', ['surfer_id'], unique=False)
    op.drop_index(op.f('ix_xp_created'), table_name='xp_transactions')
    op.drop_index(op.f('ix_xp_transactions_created'), table_name='xp_transactions')
    op.drop_index(op.f('ix_xp_transactions_user'), table_name='xp_transactions')
    op.drop_index(op.f('ix_xp_user'), table_name='xp_transactions')
    op.create_index(op.f('ix_xp_transactions_created_at'), 'xp_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_xp_transactions_user_id'), 'xp_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xp_transactions_user_id'), table_name='xp_transactions')
    op.drop_index(op.f('ix_xp_transactions_created_at'), table_name='xp_transactions')
    op.create_index(op.f('ix_xp_user'), 'xp_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_xp_transactions_user'), 'xp_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_xp_transactions_created'), 'xp_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_xp_created'), 'xp_transactions', ['created_at'], unique=False)
    op.drop_index(op.f('ix_sponsorships_surfer_id'), table_name='sponsorships')
    op.create_index(op.f('ix_sponsorships_surfer'), 'sponsorships', ['surfer_id'], unique=False)
    op.drop_index(op.f('ix_social_live_streams_broadcaster_id'), table_name='social_live_streams')
    op.create_index(op.f('idx_social_live_streams_broadcaster'), 'social_live_streams', ['broadcaster_id'], unique=False)
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewee_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_live_session_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index('ix_review_session_unique', table_name='reviews')
    op.create_index(op.f('ix_reviews_session'), 'reviews', ['live_session_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewee'), 'reviews', ['reviewee_id'], unique=False)
    op.create_index(op.f('ix_reviews_created'), 'reviews', ['created_at'], unique=False)
    op.add_column('profiles', sa.Column('equipment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'parental_controls')
    op.drop_column('profiles', 'parent_age_verified')
    op.drop_column('profiles', 'parent_link_approved')
    op.drop_column('profiles', 'guardian_code')
    op.drop_column('profiles', 'birthdate')
    op.drop_index(op.f('ix_photographer_availability_photographer_id'), table_name='photographer_availability')
    op.create_index(op.f('idx_availability_photographer'), 'photographer_availability', ['photographer_id'], unique=False)
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.create_unique_constraint(op.f('notification_preferences_user_id_key'), 'notification_preferences', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_index(op.f('idx_messages_reply_to'), 'messages', ['reply_to_id'], unique=False, postgresql_where='(reply_to_id IS NOT NULL)')
    op.drop_constraint(None, 'live_session_participants', type_='foreignkey')
    op.drop_index(op.f('ix_live_session_participants_live_session_id'), table_name='live_session_participants')
    op.create_index(op.f('idx_live_session_participants_live_session_id'), 'live_session_participants', ['live_session_id'], unique=False)
    op.drop_index(op.f('ix_gold_pass_bookings_photographer_id'), table_name='gold_pass_bookings')
    op.create_index(op.f('ix_gold_pass_photographer'), 'gold_pass_bookings', ['photographer_id'], unique=False)
    op.create_index(op.f('idx_unique_conversation_pair'), 'conversations', [sa.literal_column('LEAST(participant_one_id, participant_two_id)'), sa.literal_column('GREATEST(participant_one_id, participant_two_id)')], unique=True)
    op.drop_index(op.f('ix_condition_reports_spot_id'), table_name='condition_reports')
    op.drop_index(op.f('ix_condition_reports_region'), table_name='condition_reports')
    op.drop_index(op.f('ix_condition_reports_photographer_id'), table_name='condition_reports')
    op.drop_index(op.f('ix_condition_reports_created_at'), table_name='condition_reports')
    op.create_index(op.f('idx_condition_reports_region'), 'condition_reports', ['region'], unique=False)
    op.create_index(op.f('idx_condition_reports_photographer'), 'condition_reports', ['photographer_id'], unique=False)
    op.create_index(op.f('idx_condition_reports_created'), 'condition_reports', ['created_at'], unique=False)
    op.drop_index(op.f('ix_competition_results_surfer_id'), table_name='competition_results')
    op.create_index(op.f('ix_competition_results_surfer'), 'competition_results', ['surfer_id'], unique=False)
    op.drop_index(op.f('ix_badges_user_id'), table_name='badges')
    # ### end Alembic commands ###
