"""add_photo_tag_and_analytics_models

Revision ID: 441e0ddbfd24
Revises: 6ee7f6cda8b2
Create Date: 2026-03-15 02:22:11.201908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441e0ddbfd24'
down_revision: Union[str, Sequence[str], None] = '6ee7f6cda8b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('event_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('photo_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gallery_item_id', sa.String(length=36), nullable=False),
    sa.Column('surfer_id', sa.String(length=36), nullable=False),
    sa.Column('photographer_id', sa.String(length=36), nullable=False),
    sa.Column('live_session_id', sa.String(length=36), nullable=True),
    sa.Column('was_session_participant', sa.Boolean(), nullable=True),
    sa.Column('session_photo_price', sa.Float(), nullable=True),
    sa.Column('access_granted', sa.Boolean(), nullable=True),
    sa.Column('is_gift', sa.Boolean(), nullable=True),
    sa.Column('tagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gallery_item_id'], ['gallery_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photographer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surfer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_tags_gallery_item_id'), 'photo_tags', ['gallery_item_id'], unique=False)
    op.create_index(op.f('ix_photo_tags_live_session_id'), 'photo_tags', ['live_session_id'], unique=False)
    op.create_index(op.f('ix_photo_tags_photographer_id'), 'photo_tags', ['photographer_id'], unique=False)
    op.create_index(op.f('ix_photo_tags_surfer_id'), 'photo_tags', ['surfer_id'], unique=False)
    op.create_index(op.f('ix_photo_tags_tagged_at'), 'photo_tags', ['tagged_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_tags_tagged_at'), table_name='photo_tags')
    op.drop_index(op.f('ix_photo_tags_surfer_id'), table_name='photo_tags')
    op.drop_index(op.f('ix_photo_tags_photographer_id'), table_name='photo_tags')
    op.drop_index(op.f('ix_photo_tags_live_session_id'), table_name='photo_tags')
    op.drop_index(op.f('ix_photo_tags_gallery_item_id'), table_name='photo_tags')
    op.drop_table('photo_tags')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
