"""Add weekly challenges

Revision ID: 4af0ef8c86bc
Revises: 8ce9a5018daa
Create Date: 2026-03-15 04:04:29.470392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af0ef8c86bc'
down_revision: Union[str, Sequence[str], None] = '8ce9a5018daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('challenge_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('badge_name', sa.String(length=100), nullable=True),
    sa.Column('badge_emoji', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('challenge_id', sa.String(length=36), nullable=False),
    sa.Column('photographer_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('groms_supported', sa.Integer(), nullable=True),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('earned_trophy', sa.Boolean(), nullable=True),
    sa.Column('last_contribution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['weekly_challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photographer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_participants_challenge_id'), 'challenge_participants', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_participants_photographer_id'), 'challenge_participants', ['photographer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_participants_photographer_id'), table_name='challenge_participants')
    op.drop_index(op.f('ix_challenge_participants_challenge_id'), table_name='challenge_participants')
    op.drop_table('challenge_participants')
    op.drop_table('weekly_challenges')
    # ### end Alembic commands ###
