"""add time_windows and tide_states to surf_alerts

Revision ID: 4bc6043c0cc3
Revises: eab0f3200a56
Create Date: 2026-04-08 06:20:52.857833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc6043c0cc3'
down_revision: Union[str, Sequence[str], None] = 'eab0f3200a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surf_alerts', sa.Column('time_windows', sa.JSON(), nullable=True))
    op.add_column('surf_alerts', sa.Column('tide_states', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surf_alerts', 'tide_states')
    op.drop_column('surf_alerts', 'time_windows')
    # ### end Alembic commands ###
