"""add_gallery_livesession_skill_filter_models

Revision ID: 6ee7f6cda8b2
Revises: f574a7d3317e
Create Date: 2026-03-15 01:41:41.741194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee7f6cda8b2'
down_revision: Union[str, Sequence[str], None] = 'f574a7d3317e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('photographer_id', sa.String(length=36), nullable=False),
    sa.Column('surf_spot_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('buyin_price', sa.Float(), nullable=True),
    sa.Column('photo_price', sa.Float(), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=True),
    sa.Column('total_earnings', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_mins', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['photographer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surf_spot_id'], ['surf_spots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_sessions_photographer_id'), 'live_sessions', ['photographer_id'], unique=False)
    op.create_index(op.f('ix_live_sessions_surf_spot_id'), 'live_sessions', ['surf_spot_id'], unique=False)
    op.create_table('galleries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('photographer_id', sa.String(length=36), nullable=False),
    sa.Column('live_session_id', sa.String(length=36), nullable=True),
    sa.Column('surf_spot_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('price_web', sa.Float(), nullable=True),
    sa.Column('price_standard', sa.Float(), nullable=True),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.Column('price_720p', sa.Float(), nullable=True),
    sa.Column('price_1080p', sa.Float(), nullable=True),
    sa.Column('price_4k', sa.Float(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('purchase_count', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photographer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surf_spot_id'], ['surf_spots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galleries_created_at'), 'galleries', ['created_at'], unique=False)
    op.create_index(op.f('ix_galleries_live_session_id'), 'galleries', ['live_session_id'], unique=False)
    op.create_index(op.f('ix_galleries_photographer_id'), 'galleries', ['photographer_id'], unique=False)
    op.create_index(op.f('ix_galleries_surf_spot_id'), 'galleries', ['surf_spot_id'], unique=False)
    op.add_column('bookings', sa.Column('surf_spot_id', sa.String(length=36), nullable=True))
    op.add_column('bookings', sa.Column('skill_level_filter', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_bookings_surf_spot_id'), 'bookings', ['surf_spot_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'surf_spots', ['surf_spot_id'], ['id'], ondelete='SET NULL')
    op.add_column('gallery_items', sa.Column('gallery_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_gallery_items_gallery_id'), 'gallery_items', ['gallery_id'], unique=False)
    op.create_foreign_key(None, 'gallery_items', 'galleries', ['gallery_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gallery_items', type_='foreignkey')
    op.drop_index(op.f('ix_gallery_items_gallery_id'), table_name='gallery_items')
    op.drop_column('gallery_items', 'gallery_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_surf_spot_id'), table_name='bookings')
    op.drop_column('bookings', 'skill_level_filter')
    op.drop_column('bookings', 'surf_spot_id')
    op.drop_index(op.f('ix_galleries_surf_spot_id'), table_name='galleries')
    op.drop_index(op.f('ix_galleries_photographer_id'), table_name='galleries')
    op.drop_index(op.f('ix_galleries_live_session_id'), table_name='galleries')
    op.drop_index(op.f('ix_galleries_created_at'), table_name='galleries')
    op.drop_table('galleries')
    op.drop_index(op.f('ix_live_sessions_surf_spot_id'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_photographer_id'), table_name='live_sessions')
    op.drop_table('live_sessions')
    # ### end Alembic commands ###
