"""Add SurfReport model

Revision ID: 6efd1135056a
Revises: 849264a48cf3
Create Date: 2026-03-14 16:08:49.918327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efd1135056a'
down_revision: Union[str, Sequence[str], None] = '849264a48cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surf_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('spot_id', sa.String(length=36), nullable=False),
    sa.Column('wave_height', sa.String(length=50), nullable=True),
    sa.Column('conditions', sa.String(length=100), nullable=True),
    sa.Column('wind_direction', sa.String(length=50), nullable=True),
    sa.Column('crowd_level', sa.String(length=50), nullable=True),
    sa.Column('water_temp', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['surf_spots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surf_reports_created_at'), 'surf_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_surf_reports_spot_id'), 'surf_reports', ['spot_id'], unique=False)
    op.create_index(op.f('ix_surf_reports_user_id'), 'surf_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surf_reports_user_id'), table_name='surf_reports')
    op.drop_index(op.f('ix_surf_reports_spot_id'), table_name='surf_reports')
    op.drop_index(op.f('ix_surf_reports_created_at'), table_name='surf_reports')
    op.drop_table('surf_reports')
    # ### end Alembic commands ###
