"""add dynamic pricing fields

Revision ID: 720f8f4fcb5e
Revises: 4af0ef8c86bc
Create Date: 2026-03-15 04:31:10.510057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720f8f4fcb5e'
down_revision: Union[str, Sequence[str], None] = '4af0ef8c86bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery_items', sa.Column('custom_price', sa.Float(), nullable=True))
    op.add_column('live_sessions', sa.Column('session_photo_price', sa.Float(), nullable=True))
    op.add_column('live_sessions', sa.Column('session_video_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_sessions', 'session_video_price')
    op.drop_column('live_sessions', 'session_photo_price')
    op.drop_column('gallery_items', 'custom_price')
    # ### end Alembic commands ###
