"""add_friends_messenger_v2

Revision ID: 872fd5e2e5b0
Revises: c8105e7c3c9e
Create Date: 2026-03-15 06:34:31.666282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872fd5e2e5b0'
down_revision: Union[str, Sequence[str], None] = 'c8105e7c3c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('addressee_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'BLOCKED', name='friendshipstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friends_addressee_id'), 'friends', ['addressee_id'], unique=False)
    op.create_index('ix_friends_pair', 'friends', ['requester_id', 'addressee_id'], unique=True)
    op.create_index(op.f('ix_friends_requester_id'), 'friends', ['requester_id'], unique=False)
    op.create_index(op.f('ix_friends_status'), 'friends', ['status'], unique=False)
    op.create_table('privacy_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('map_visibility', sa.String(length=20), nullable=True),
    sa.Column('is_ghost_mode', sa.Boolean(), nullable=True),
    sa.Column('allow_proximity_pings', sa.Boolean(), nullable=True),
    sa.Column('show_online_status', sa.Boolean(), nullable=True),
    sa.Column('show_last_seen', sa.Boolean(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('gps_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_privacy_settings_user_id'), 'privacy_settings', ['user_id'], unique=True)
    op.create_table('conversation_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=True),
    sa.Column('muted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conv_participants_pair', 'conversation_participants', ['conversation_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_user_id'), 'conversation_participants', ['user_id'], unique=False)
    op.create_table('typing_indicators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typing_indicators_conversation_id'), 'typing_indicators', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_typing_indicators_user_id'), 'typing_indicators', ['user_id'], unique=False)
    op.create_index('ix_typing_pair', 'typing_indicators', ['conversation_id', 'user_id'], unique=True)
    op.create_table('message_reactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_reactions_message_id'), 'message_reactions', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_reactions_user_id'), 'message_reactions', ['user_id'], unique=False)
    op.create_index('ix_msg_reactions_pair', 'message_reactions', ['message_id', 'user_id', 'emoji'], unique=True)
    op.create_table('message_read_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_read_receipts_message_id'), 'message_read_receipts', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_read_receipts_user_id'), 'message_read_receipts', ['user_id'], unique=False)
    op.create_index('ix_msg_read_pair', 'message_read_receipts', ['message_id', 'user_id'], unique=True)
    op.create_table('voice_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('waveform_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_notes_message_id'), 'voice_notes', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_notes_message_id'), table_name='voice_notes')
    op.drop_table('voice_notes')
    op.drop_index('ix_msg_read_pair', table_name='message_read_receipts')
    op.drop_index(op.f('ix_message_read_receipts_user_id'), table_name='message_read_receipts')
    op.drop_index(op.f('ix_message_read_receipts_message_id'), table_name='message_read_receipts')
    op.drop_table('message_read_receipts')
    op.drop_index('ix_msg_reactions_pair', table_name='message_reactions')
    op.drop_index(op.f('ix_message_reactions_user_id'), table_name='message_reactions')
    op.drop_index(op.f('ix_message_reactions_message_id'), table_name='message_reactions')
    op.drop_table('message_reactions')
    op.drop_index('ix_typing_pair', table_name='typing_indicators')
    op.drop_index(op.f('ix_typing_indicators_user_id'), table_name='typing_indicators')
    op.drop_index(op.f('ix_typing_indicators_conversation_id'), table_name='typing_indicators')
    op.drop_table('typing_indicators')
    op.drop_index(op.f('ix_conversation_participants_user_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_index('ix_conv_participants_pair', table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_privacy_settings_user_id'), table_name='privacy_settings')
    op.drop_table('privacy_settings')
    op.drop_index(op.f('ix_friends_status'), table_name='friends')
    op.drop_index(op.f('ix_friends_requester_id'), table_name='friends')
    op.drop_index('ix_friends_pair', table_name='friends')
    op.drop_index(op.f('ix_friends_addressee_id'), table_name='friends')
    op.drop_table('friends')
    # ### end Alembic commands ###
