"""Add SmugMug pricing and credit transactions

Revision ID: 88fe5fa2539f
Revises: 2eba5ff663be
Create Date: 2026-03-15 00:49:57.702352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88fe5fa2539f'
down_revision: Union[str, Sequence[str], None] = '2eba5ff663be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_before', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('counterparty_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_created_at'), 'credit_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.add_column('profiles', sa.Column('live_buyin_price', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('live_photo_price', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('photo_package_size', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('booking_hourly_rate', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('booking_min_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'booking_min_hours')
    op.drop_column('profiles', 'booking_hourly_rate')
    op.drop_column('profiles', 'photo_package_size')
    op.drop_column('profiles', 'live_photo_price')
    op.drop_column('profiles', 'live_buyin_price')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_created_at'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    # ### end Alembic commands ###
