"""Add impact ledger and leaderboard snapshot

Revision ID: 8ce9a5018daa
Revises: 2f7c6bd5fa7d
Create Date: 2026-03-15 03:49:53.885683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce9a5018daa'
down_revision: Union[str, Sequence[str], None] = '2f7c6bd5fa7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('photographer_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=True),
    sa.Column('cause_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['photographer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_ledger_photographer_id'), 'impact_ledger', ['photographer_id'], unique=False)
    op.create_table('leaderboard_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('photographer_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('monthly_total', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('earned_grom_guardian', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['photographer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_snapshots_photographer_id'), 'leaderboard_snapshots', ['photographer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_snapshots_photographer_id'), table_name='leaderboard_snapshots')
    op.drop_table('leaderboard_snapshots')
    op.drop_index(op.f('ix_impact_ledger_photographer_id'), table_name='impact_ledger')
    op.drop_table('impact_ledger')
    # ### end Alembic commands ###
