"""Add video support and user_media table

Revision ID: 9930f5ad0662
Revises: bdae2a97f3ab
Create Date: 2026-03-14 20:25:48.731990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9930f5ad0662'
down_revision: Union[str, Sequence[str], None] = 'bdae2a97f3ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('source_photographer_id', sa.String(length=36), nullable=True),
    sa.Column('source_gallery_item_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_width', sa.Integer(), nullable=True),
    sa.Column('video_height', sa.Integer(), nullable=True),
    sa.Column('video_duration', sa.Float(), nullable=True),
    sa.Column('was_transcoded', sa.Boolean(), nullable=True),
    sa.Column('original_width', sa.Integer(), nullable=True),
    sa.Column('original_height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_gallery_item_id'], ['gallery_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_photographer_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_media_created_at'), 'user_media', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_media_user_id'), 'user_media', ['user_id'], unique=False)
    op.add_column('gallery_items', sa.Column('media_type', sa.String(length=20), nullable=True))
    op.add_column('gallery_items', sa.Column('video_width', sa.Integer(), nullable=True))
    op.add_column('gallery_items', sa.Column('video_height', sa.Integer(), nullable=True))
    op.add_column('gallery_items', sa.Column('video_duration', sa.Float(), nullable=True))
    
    # First add media_url as nullable and copy data from image_url
    op.add_column('posts', sa.Column('media_url', sa.String(length=500), nullable=True))
    op.execute("UPDATE posts SET media_url = image_url WHERE image_url IS NOT NULL")
    op.execute("UPDATE posts SET media_url = 'https://placeholder.com/missing.jpg' WHERE media_url IS NULL")
    op.alter_column('posts', 'media_url', nullable=False)
    
    op.add_column('posts', sa.Column('media_type', sa.String(length=20), nullable=True))
    op.add_column('posts', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('posts', sa.Column('video_width', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('video_height', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('video_duration', sa.Float(), nullable=True))
    op.add_column('posts', sa.Column('was_transcoded', sa.Boolean(), nullable=True))
    
    # Set default media_type for existing posts
    op.execute("UPDATE posts SET media_type = 'image' WHERE media_type IS NULL")
    
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('posts', 'was_transcoded')
    op.drop_column('posts', 'video_duration')
    op.drop_column('posts', 'video_height')
    op.drop_column('posts', 'video_width')
    op.drop_column('posts', 'thumbnail_url')
    op.drop_column('posts', 'media_type')
    op.drop_column('posts', 'media_url')
    op.drop_column('gallery_items', 'video_duration')
    op.drop_column('gallery_items', 'video_height')
    op.drop_column('gallery_items', 'video_width')
    op.drop_column('gallery_items', 'media_type')
    op.drop_index(op.f('ix_user_media_user_id'), table_name='user_media')
    op.drop_index(op.f('ix_user_media_created_at'), table_name='user_media')
    op.drop_table('user_media')
    # ### end Alembic commands ###
