"""add_username_system

Revision ID: a7d7707b4da2
Revises: 16d4062ae064
Create Date: 2026-04-07 04:37:29.017516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d7707b4da2'
down_revision: Union[str, Sequence[str], None] = '16d4062ae064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('username_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('previous_owner_id', sa.String(length=36), nullable=False),
    sa.Column('claimed_by_id', sa.String(length=36), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_owner_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_username_history_previous_owner_id'), 'username_history', ['previous_owner_id'], unique=False)
    op.create_index(op.f('ix_username_history_username'), 'username_history', ['username'], unique=False)
    op.add_column('profiles', sa.Column('username', sa.String(length=30), nullable=True))
    op.add_column('profiles', sa.Column('username_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_profiles_username'), 'profiles', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_username'), table_name='profiles')
    op.drop_column('profiles', 'username_changed_at')
    op.drop_column('profiles', 'username')
    op.drop_index(op.f('ix_username_history_username'), table_name='username_history')
    op.drop_index(op.f('ix_username_history_previous_owner_id'), table_name='username_history')
    op.drop_table('username_history')
    # ### end Alembic commands ###
