"""add_post_likes_unique_constraint

Revision ID: ae6067f391dd
Revises: b30950da1d64
Create Date: 2026-03-14 22:44:37.562236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6067f391dd'
down_revision: Union[str, Sequence[str], None] = 'b30950da1d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_post_likes_post_user', 'post_likes', ['post_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_likes_post_user', table_name='post_likes')
    # ### end Alembic commands ###
