"""Add gallery admin models

Revision ID: bdae2a97f3ab
Revises: c28cb2e592da
Create Date: 2026-03-14 17:19:18.407697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdae2a97f3ab'
down_revision: Union[str, Sequence[str], None] = 'c28cb2e592da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_logs_admin_id'), 'admin_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_logs_created_at'), 'admin_logs', ['created_at'], unique=False)
    op.create_table('gallery_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('photographer_id', sa.String(length=36), nullable=False),
    sa.Column('spot_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('preview_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_for_sale', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('purchase_count', sa.Integer(), nullable=True),
    sa.Column('tagged_surfer_ids', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shot_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['photographer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spot_id'], ['surf_spots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_items_created_at'), 'gallery_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_gallery_items_photographer_id'), 'gallery_items', ['photographer_id'], unique=False)
    op.create_index(op.f('ix_gallery_items_spot_id'), 'gallery_items', ['spot_id'], unique=False)
    op.create_table('gallery_purchases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gallery_item_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('photographer_id', sa.String(length=36), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('max_downloads', sa.Integer(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gallery_item_id'], ['gallery_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photographer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_purchases_buyer_id'), 'gallery_purchases', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_gallery_purchases_gallery_item_id'), 'gallery_purchases', ['gallery_item_id'], unique=False)
    op.add_column('profiles', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('is_suspended', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('suspended_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'suspended_reason')
    op.drop_column('profiles', 'suspended_at')
    op.drop_column('profiles', 'is_suspended')
    op.drop_column('profiles', 'is_admin')
    op.drop_index(op.f('ix_gallery_purchases_gallery_item_id'), table_name='gallery_purchases')
    op.drop_index(op.f('ix_gallery_purchases_buyer_id'), table_name='gallery_purchases')
    op.drop_table('gallery_purchases')
    op.drop_index(op.f('ix_gallery_items_spot_id'), table_name='gallery_items')
    op.drop_index(op.f('ix_gallery_items_photographer_id'), table_name='gallery_items')
    op.drop_index(op.f('ix_gallery_items_created_at'), table_name='gallery_items')
    op.drop_table('gallery_items')
    op.drop_index(op.f('ix_admin_logs_created_at'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_admin_id'), table_name='admin_logs')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
