"""Add stories and story_views tables

Revision ID: c28cb2e592da
Revises: c8228006f277
Create Date: 2026-03-14 16:55:06.971204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28cb2e592da'
down_revision: Union[str, Sequence[str], None] = 'c8228006f277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('spot_id', sa.String(length=36), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('story_type', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('is_live_report', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spot_id'], ['surf_spots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_author_id'), 'stories', ['author_id'], unique=False)
    op.create_index(op.f('ix_stories_created_at'), 'stories', ['created_at'], unique=False)
    op.create_index(op.f('ix_stories_spot_id'), 'stories', ['spot_id'], unique=False)
    op.create_table('story_views',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('viewer_id', sa.String(length=36), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_views_story_id'), 'story_views', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_views_viewer_id'), 'story_views', ['viewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_views_viewer_id'), table_name='story_views')
    op.drop_index(op.f('ix_story_views_story_id'), table_name='story_views')
    op.drop_table('story_views')
    op.drop_index(op.f('ix_stories_spot_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_created_at'), table_name='stories')
    op.drop_index(op.f('ix_stories_author_id'), table_name='stories')
    op.drop_table('stories')
    # ### end Alembic commands ###
