"""Add subscription and profile fields

Revision ID: c48421a9bf58
Revises: 60b6c3ac3542
Create Date: 2026-03-14 05:13:24.163011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48421a9bf58'
down_revision: Union[str, Sequence[str], None] = '60b6c3ac3542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('subscription_tier', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('is_approved_pro', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('portfolio_url', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('instagram_url', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('website_url', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('hourly_rate', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('session_price', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('accepts_donations', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('skill_level', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('stance', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('home_break', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'home_break')
    op.drop_column('profiles', 'stance')
    op.drop_column('profiles', 'skill_level')
    op.drop_column('profiles', 'accepts_donations')
    op.drop_column('profiles', 'session_price')
    op.drop_column('profiles', 'hourly_rate')
    op.drop_column('profiles', 'website_url')
    op.drop_column('profiles', 'instagram_url')
    op.drop_column('profiles', 'portfolio_url')
    op.drop_column('profiles', 'company_name')
    op.drop_column('profiles', 'is_approved_pro')
    op.drop_column('profiles', 'is_private')
    op.drop_column('profiles', 'subscription_tier')
    # ### end Alembic commands ###
