"""add_dispatch_system

Revision ID: c8105e7c3c9e
Revises: 720f8f4fcb5e
Create Date: 2026-03-15 06:18:19.283370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8105e7c3c9e'
down_revision: Union[str, Sequence[str], None] = '720f8f4fcb5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('spot_id', sa.String(length=36), nullable=True),
    sa.Column('estimated_duration_hours', sa.Float(), nullable=True),
    sa.Column('requested_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_immediate', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'SEARCHING_FOR_PRO', 'ACCEPTED', 'EN_ROUTE', 'ARRIVED', 'COMPLETED', 'CANCELLED', 'NO_PRO_FOUND', 'REFUNDED', name='dispatchrequeststatusenum'), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatch_stage', sa.Integer(), nullable=True),
    sa.Column('stage_1_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_2_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_radius_miles', sa.Float(), nullable=True),
    sa.Column('photographer_id', sa.String(length=36), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photographer_lat', sa.Float(), nullable=True),
    sa.Column('photographer_lng', sa.Float(), nullable=True),
    sa.Column('photographer_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requester_lat', sa.Float(), nullable=True),
    sa.Column('requester_lng', sa.Float(), nullable=True),
    sa.Column('requester_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_arrival_minutes', sa.Integer(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('estimated_total', sa.Float(), nullable=False),
    sa.Column('deposit_pct', sa.Integer(), nullable=True),
    sa.Column('deposit_amount', sa.Float(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('deposit_paid', sa.Boolean(), nullable=True),
    sa.Column('deposit_paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.String(length=36), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('refund_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photographer_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spot_id'], ['surf_spots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_requests_photographer_id'), 'dispatch_requests', ['photographer_id'], unique=False)
    op.create_index(op.f('ix_dispatch_requests_requester_id'), 'dispatch_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_dispatch_requests_status'), 'dispatch_requests', ['status'], unique=False)
    op.create_table('dispatch_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dispatch_request_id', sa.String(length=36), nullable=False),
    sa.Column('photographer_id', sa.String(length=36), nullable=False),
    sa.Column('dispatch_stage', sa.Integer(), nullable=False),
    sa.Column('distance_miles', sa.Float(), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response', sa.String(length=20), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_request_id'], ['dispatch_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photographer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_notifications_dispatch_request_id'), 'dispatch_notifications', ['dispatch_request_id'], unique=False)
    op.create_index(op.f('ix_dispatch_notifications_photographer_id'), 'dispatch_notifications', ['photographer_id'], unique=False)
    op.create_table('dispatch_request_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dispatch_request_id', sa.String(length=36), nullable=False),
    sa.Column('participant_id', sa.String(length=36), nullable=False),
    sa.Column('share_amount', sa.Float(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_request_id'], ['dispatch_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_request_participants_dispatch_request_id'), 'dispatch_request_participants', ['dispatch_request_id'], unique=False)
    op.create_index(op.f('ix_dispatch_request_participants_participant_id'), 'dispatch_request_participants', ['participant_id'], unique=False)
    op.add_column('profiles', sa.Column('is_available_on_demand', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('on_demand_hourly_rate', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('on_demand_radius_miles', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('booking_deposit_pct', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'booking_deposit_pct')
    op.drop_column('profiles', 'on_demand_radius_miles')
    op.drop_column('profiles', 'on_demand_hourly_rate')
    op.drop_column('profiles', 'is_available_on_demand')
    op.drop_index(op.f('ix_dispatch_request_participants_participant_id'), table_name='dispatch_request_participants')
    op.drop_index(op.f('ix_dispatch_request_participants_dispatch_request_id'), table_name='dispatch_request_participants')
    op.drop_table('dispatch_request_participants')
    op.drop_index(op.f('ix_dispatch_notifications_photographer_id'), table_name='dispatch_notifications')
    op.drop_index(op.f('ix_dispatch_notifications_dispatch_request_id'), table_name='dispatch_notifications')
    op.drop_table('dispatch_notifications')
    op.drop_index(op.f('ix_dispatch_requests_status'), table_name='dispatch_requests')
    op.drop_index(op.f('ix_dispatch_requests_requester_id'), table_name='dispatch_requests')
    op.drop_index(op.f('ix_dispatch_requests_photographer_id'), table_name='dispatch_requests')
    op.drop_table('dispatch_requests')
    # ### end Alembic commands ###
