"""Add SurfAlert and PushSubscription models

Revision ID: c8228006f277
Revises: 6efd1135056a
Create Date: 2026-03-14 16:27:31.949332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8228006f277'
down_revision: Union[str, Sequence[str], None] = '6efd1135056a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh_key', sa.String(length=255), nullable=False),
    sa.Column('auth_key', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('surf_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('spot_id', sa.String(length=36), nullable=False),
    sa.Column('min_wave_height', sa.Float(), nullable=True),
    sa.Column('max_wave_height', sa.Float(), nullable=True),
    sa.Column('preferred_conditions', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notify_push', sa.Boolean(), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=True),
    sa.Column('last_triggered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['surf_spots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surf_alerts_spot_id'), 'surf_alerts', ['spot_id'], unique=False)
    op.create_index(op.f('ix_surf_alerts_user_id'), 'surf_alerts', ['user_id'], unique=False)
    op.add_column('surf_reports', sa.Column('tide_height', sa.String(length=50), nullable=True))
    op.add_column('surf_reports', sa.Column('tide_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surf_reports', 'tide_status')
    op.drop_column('surf_reports', 'tide_height')
    op.drop_index(op.f('ix_surf_alerts_user_id'), table_name='surf_alerts')
    op.drop_index(op.f('ix_surf_alerts_spot_id'), table_name='surf_alerts')
    op.drop_table('surf_alerts')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
