"""add_default_watermark_in_selection_to_profile

Revision ID: c89872c7b8ae
Revises: 10279d0ca1fd
Create Date: 2026-04-07 03:36:50.320094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89872c7b8ae'
down_revision: Union[str, Sequence[str], None] = '10279d0ca1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('default_watermark_in_selection', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'default_watermark_in_selection')
    # ### end Alembic commands ###
