"""add_is_favorite_to_surfer_gallery_items

Revision ID: d42bb546bc54
Revises: 3fd4454229d5
Create Date: 2026-04-07 01:20:43.492106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd42bb546bc54'
down_revision: Union[str, Sequence[str], None] = '3fd4454229d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking_participants', 'share_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('booking_participants', 'share_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('booking_participants', 'covered_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_index(op.f('ix_comment_reactions_comment'), table_name='comment_reactions')
    op.drop_index(op.f('ix_comment_reactions_user'), table_name='comment_reactions')
    op.alter_column('crew_chat_messages', 'system_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('crew_chat_messages', 'read_by',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('crew_chat_messages', 'reactions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('crew_chat_messages', 'mentions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_crew_chat_messages_reply_to'), table_name='crew_chat_messages')
    op.create_foreign_key(None, 'crew_chat_messages', 'profiles', ['sender_id'], ['id'], ondelete='CASCADE')
    op.alter_column('global_pricing_config', 'pricing_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index(op.f('idx_pricing_config_active'), table_name='global_pricing_config')
    op.drop_column('messages', 'mentions')
    op.drop_constraint(op.f('photographer_alert_subscripti_user_id_photographer_id_alert_key'), 'photographer_alert_subscriptions', type_='unique')
    op.create_index('idx_photographer_alert_unique', 'photographer_alert_subscriptions', ['user_id', 'photographer_id', 'alert_type'], unique=True)
    op.drop_index(op.f('idx_photographer_requests_requester'), table_name='photographer_requests')
    op.drop_index(op.f('idx_photographer_requests_spot'), table_name='photographer_requests')
    op.drop_index(op.f('idx_photographer_requests_status'), table_name='photographer_requests')
    op.alter_column('posts', 'carousel_media',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_foreign_key(None, 'posts', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    op.alter_column('profiles', 'meta_connections',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('saved_crews', 'members',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_saved_crews_default'), table_name='saved_crews', postgresql_where='(is_default = true)')
    op.drop_index(op.f('idx_saved_crews_owner'), table_name='saved_crews')
    op.create_index(op.f('ix_saved_crews_owner_id'), 'saved_crews', ['owner_id'], unique=False)
    op.drop_index(op.f('idx_spot_edit_logs_spot'), table_name='spot_edit_logs')
    op.drop_index(op.f('idx_spot_verifications_spot'), table_name='spot_verifications')
    op.drop_index(op.f('idx_surf_spots_country'), table_name='surf_spots')
    op.drop_index(op.f('idx_surf_spots_osm_id'), table_name='surf_spots')
    op.create_index(op.f('ix_surf_spots_country'), 'surf_spots', ['country'], unique=False)
    op.create_index(op.f('ix_surf_spots_osm_id'), 'surf_spots', ['osm_id'], unique=False)
    op.drop_index(op.f('ix_claim_queue_created_at'), table_name='surfer_gallery_claim_queue')
    op.drop_index(op.f('ix_claim_queue_surfer_id'), table_name='surfer_gallery_claim_queue')
    op.add_column('surfer_gallery_items', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_surfer_gallery_added_at'), table_name='surfer_gallery_items')
    op.drop_index(op.f('ix_surfer_gallery_surfer_id'), table_name='surfer_gallery_items')
    op.drop_index(op.f('ix_selection_quota_surfer'), table_name='surfer_selection_quotas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_selection_quota_surfer'), 'surfer_selection_quotas', ['surfer_id'], unique=False)
    op.create_index(op.f('ix_surfer_gallery_surfer_id'), 'surfer_gallery_items', ['surfer_id'], unique=False)
    op.create_index(op.f('ix_surfer_gallery_added_at'), 'surfer_gallery_items', ['added_at'], unique=False)
    op.drop_column('surfer_gallery_items', 'is_favorite')
    op.create_index(op.f('ix_claim_queue_surfer_id'), 'surfer_gallery_claim_queue', ['surfer_id'], unique=False)
    op.create_index(op.f('ix_claim_queue_created_at'), 'surfer_gallery_claim_queue', ['created_at'], unique=False)
    op.drop_index(op.f('ix_surf_spots_osm_id'), table_name='surf_spots')
    op.drop_index(op.f('ix_surf_spots_country'), table_name='surf_spots')
    op.create_index(op.f('idx_surf_spots_osm_id'), 'surf_spots', ['osm_id'], unique=False)
    op.create_index(op.f('idx_surf_spots_country'), 'surf_spots', ['country'], unique=False)
    op.create_index(op.f('idx_spot_verifications_spot'), 'spot_verifications', ['spot_id'], unique=False)
    op.create_index(op.f('idx_spot_edit_logs_spot'), 'spot_edit_logs', ['spot_id'], unique=False)
    op.drop_index(op.f('ix_saved_crews_owner_id'), table_name='saved_crews')
    op.create_index(op.f('idx_saved_crews_owner'), 'saved_crews', ['owner_id'], unique=False)
    op.create_index(op.f('idx_saved_crews_default'), 'saved_crews', ['owner_id', 'is_default'], unique=False, postgresql_where='(is_default = true)')
    op.alter_column('saved_crews', 'members',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('profiles', 'meta_connections',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'carousel_media',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('idx_photographer_requests_status'), 'photographer_requests', ['status'], unique=False)
    op.create_index(op.f('idx_photographer_requests_spot'), 'photographer_requests', ['spot_id'], unique=False)
    op.create_index(op.f('idx_photographer_requests_requester'), 'photographer_requests', ['requester_id'], unique=False)
    op.drop_index('idx_photographer_alert_unique', table_name='photographer_alert_subscriptions')
    op.create_unique_constraint(op.f('photographer_alert_subscripti_user_id_photographer_id_alert_key'), 'photographer_alert_subscriptions', ['user_id', 'photographer_id', 'alert_type'], postgresql_nulls_not_distinct=False)
    op.add_column('messages', sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_pricing_config_active'), 'global_pricing_config', ['is_active', sa.literal_column('version DESC')], unique=False)
    op.alter_column('global_pricing_config', 'pricing_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(None, 'crew_chat_messages', type_='foreignkey')
    op.create_index(op.f('ix_crew_chat_messages_reply_to'), 'crew_chat_messages', ['reply_to_id'], unique=False)
    op.alter_column('crew_chat_messages', 'mentions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('crew_chat_messages', 'reactions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('crew_chat_messages', 'read_by',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('crew_chat_messages', 'system_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_comment_reactions_user'), 'comment_reactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_comment_reactions_comment'), 'comment_reactions', ['comment_id'], unique=False)
    op.alter_column('booking_participants', 'covered_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('booking_participants', 'share_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('booking_participants', 'share_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###
