"""Add pinned_post_id and comment_edit_fields

Revision ID: eab0f3200a56
Revises: a7d7707b4da2
Create Date: 2026-04-07 05:18:19.029356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab0f3200a56'
down_revision: Union[str, Sequence[str], None] = 'a7d7707b4da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('comments', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('pinned_post_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('profiles_username_key'), 'profiles', type_='unique')
    op.drop_index(op.f('ix_profiles_username'), table_name='profiles')
    op.create_index(op.f('ix_profiles_username'), 'profiles', ['username'], unique=True)
    op.create_foreign_key(None, 'profiles', 'posts', ['pinned_post_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_index(op.f('ix_profiles_username'), table_name='profiles')
    op.create_index(op.f('ix_profiles_username'), 'profiles', ['username'], unique=False)
    op.create_unique_constraint(op.f('profiles_username_key'), 'profiles', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('profiles', 'pinned_post_id')
    op.drop_column('comments', 'is_edited')
    op.drop_column('comments', 'edited_at')
    # ### end Alembic commands ###
