"""add_checkin_streak_badges_fields

Revision ID: eca9b463bb3e
Revises: 441e0ddbfd24
Create Date: 2026-03-15 02:48:11.160450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca9b463bb3e'
down_revision: Union[str, Sequence[str], None] = '441e0ddbfd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_check_in', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('spot_id', sa.String(length=36), nullable=True))
    op.add_column('posts', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('posts', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('posts', sa.Column('check_in_photographer_id', sa.String(length=36), nullable=True))
    op.add_column('posts', sa.Column('check_in_session_price', sa.Float(), nullable=True))
    op.alter_column('posts', 'media_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.create_index(op.f('ix_posts_is_check_in'), 'posts', ['is_check_in'], unique=False)
    op.create_foreign_key(None, 'posts', 'surf_spots', ['spot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'posts', 'profiles', ['check_in_photographer_id'], ['id'], ondelete='SET NULL')
    op.add_column('profiles', sa.Column('surf_streak', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('last_surf_date', sa.Date(), nullable=True))
    op.add_column('profiles', sa.Column('total_sessions', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('badges', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'badges')
    op.drop_column('profiles', 'total_sessions')
    op.drop_column('profiles', 'last_surf_date')
    op.drop_column('profiles', 'surf_streak')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_is_check_in'), table_name='posts')
    op.alter_column('posts', 'media_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('posts', 'check_in_session_price')
    op.drop_column('posts', 'check_in_photographer_id')
    op.drop_column('posts', 'longitude')
    op.drop_column('posts', 'latitude')
    op.drop_column('posts', 'spot_id')
    op.drop_column('posts', 'is_check_in')
    # ### end Alembic commands ###
