"""Add gallery quality tiers and pricing

Revision ID: f574a7d3317e
Revises: 88fe5fa2539f
Create Date: 2026-03-15 01:03:14.482221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f574a7d3317e'
down_revision: Union[str, Sequence[str], None] = '88fe5fa2539f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery_items', sa.Column('url_web', sa.String(length=500), nullable=True))
    op.add_column('gallery_items', sa.Column('url_standard', sa.String(length=500), nullable=True))
    op.add_column('gallery_items', sa.Column('url_720p', sa.String(length=500), nullable=True))
    op.add_column('gallery_items', sa.Column('url_1080p', sa.String(length=500), nullable=True))
    op.add_column('gallery_items', sa.Column('photo_width', sa.Integer(), nullable=True))
    op.add_column('gallery_items', sa.Column('photo_height', sa.Integer(), nullable=True))
    op.add_column('gallery_items', sa.Column('price_web', sa.Float(), nullable=True))
    op.add_column('gallery_items', sa.Column('price_standard', sa.Float(), nullable=True))
    op.add_column('gallery_items', sa.Column('price_high', sa.Float(), nullable=True))
    op.add_column('gallery_items', sa.Column('price_720p', sa.Float(), nullable=True))
    op.add_column('gallery_items', sa.Column('price_1080p', sa.Float(), nullable=True))
    op.add_column('gallery_items', sa.Column('price_4k', sa.Float(), nullable=True))
    op.add_column('gallery_purchases', sa.Column('quality_tier', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('photo_price_web', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('photo_price_standard', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('photo_price_high', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('video_price_720p', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('video_price_1080p', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('video_price_4k', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'video_price_4k')
    op.drop_column('profiles', 'video_price_1080p')
    op.drop_column('profiles', 'video_price_720p')
    op.drop_column('profiles', 'photo_price_high')
    op.drop_column('profiles', 'photo_price_standard')
    op.drop_column('profiles', 'photo_price_web')
    op.drop_column('gallery_purchases', 'quality_tier')
    op.drop_column('gallery_items', 'price_4k')
    op.drop_column('gallery_items', 'price_1080p')
    op.drop_column('gallery_items', 'price_720p')
    op.drop_column('gallery_items', 'price_high')
    op.drop_column('gallery_items', 'price_standard')
    op.drop_column('gallery_items', 'price_web')
    op.drop_column('gallery_items', 'photo_height')
    op.drop_column('gallery_items', 'photo_width')
    op.drop_column('gallery_items', 'url_1080p')
    op.drop_column('gallery_items', 'url_720p')
    op.drop_column('gallery_items', 'url_standard')
    op.drop_column('gallery_items', 'url_web')
    # ### end Alembic commands ###
