"""Add LiveSessionParticipant

Revision ID: f72f1cf1e0e0
Revises: 3c0cfb85ba5a
Create Date: 2026-03-14 14:38:41.592024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f72f1cf1e0e0'
down_revision: Union[str, Sequence[str], None] = '3c0cfb85ba5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_session_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('photographer_id', sa.String(length=36), nullable=False),
    sa.Column('surfer_id', sa.String(length=36), nullable=False),
    sa.Column('spot_id', sa.String(length=36), nullable=True),
    sa.Column('selfie_url', sa.String(length=500), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['photographer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spot_id'], ['surf_spots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['surfer_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_session_participants_photographer_id'), 'live_session_participants', ['photographer_id'], unique=False)
    op.create_index(op.f('ix_live_session_participants_surfer_id'), 'live_session_participants', ['surfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_session_participants_surfer_id'), table_name='live_session_participants')
    op.drop_index(op.f('ix_live_session_participants_photographer_id'), table_name='live_session_participants')
    op.drop_table('live_session_participants')
    # ### end Alembic commands ###
